---
- name: Comprehensive Nginx Testing
  hosts: webservers
  tasks:
    - name: Check Nginx is listening on port 80
      wait_for:
        port: 80
        host: "{{ inventory_hostname }}"
        timeout: 10
      
    - name: Test HTTP response
      uri:
        url: "http://localhost:80"
        method: GET
        return_content: true
      register: http_response
      
    - name: Verify response contains hostname
      assert:
        that:
          - http_response.status == 200
          - ansible_hostname in http_response.content
        fail_msg: "HTTP response doesn't contain expected hostname"
        success_msg: "✅ HTTP test passed for {{ ansible_hostname }}"
        
    - name: Check Nginx configuration syntax
      shell: nginx -t
      become: true
      register: nginx_syntax
      
    - name: Display syntax check result
      debug:
        msg: "{{ nginx_syntax.stderr }}"
        
    - name: Get Nginx access logs (last 5 lines)
      shell: tail -5 /var/log/nginx/access.log
      become: true
      register: access_logs
      ignore_errors: true
      
    - name: Display access logs
      debug:
        var: access_logs.stdout_lines
      when: access_logs.stdout_lines is defined